version: '3'

services:
  flask_app:
    container_name: ames_ML_prod_updated
    restart: always
    build: ./ames_ML_prod
    ports:
      - "8010:8010"
    command: gunicorn -w 1 -b 0.0.0.0:8010 wsgi:app

  nginx:
    container_name: nginx_updated
    restart: always
    build: ./nginx
    ports:
      - "82:82"
    depends_on:
      - flask_app